version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - typecheck
    - goimports
    - misspell
    - revive

linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
